id: P11F46619
initial_creation_type: ocr
source_metadata:
  volumes:
    2e1a4d13ea8a452a9fdb2fe5dc910969:
      base_file: v037.txt
      image_group_id: I1PD95882
      title: དཔལ་འབྱུང་པོ་འདུལ་བྱེད་ཀྱི་དཀྱིལ་འཁོར་གྱི་ཆོ་ག།
      total_pages: 1379
      volume_number: 37
